# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
project 'RavenExample.xcodeproj'

ENV['RCT_NEW_ARCH_ENABLED'] = '1'
ENV['USE_FABRIC'] = '0'

prepare_react_native_project!

# linkage = ENV['USE_FRAMEWORKS']
# if linkage != nil
#   Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
#   use_frameworks! :linkage => linkage.to_sym
# end
use_frameworks! :linkage => :static 

target 'RavenExample' do

  # Manually add gesture handler pod
  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'
  pod 'react-native-safe-area-context', :path => '../node_modules/react-native-safe-area-context'
  pod 'RNScreens', :path => '../node_modules/react-native-screens'
  pod 'RNReanimated', :path => '../node_modules/react-native-reanimated'
  pod 'RNWorklets', :path => '../node_modules/react-native-worklets'
  pod 'Raven', :path => '../../'
  # raven-ios-sdk is required by Raven's native code (imported in OutAppInitializer.swift)
  pod 'raven-ios-sdk', :git => 'git@github.com:dream11/raven-ios-sdk.git'

  use_react_native!(
    :path => "../node_modules/react-native",
    :hermes_enabled => true,
    :fabric_enabled => false,
    :new_arch_enabled => true,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      "../node_modules/react-native",
      :mac_catalyst_enabled => false,
      :ccache_enabled => true
    )
  end
end

# NotificationServiceExtension uses raven-ios-sdk via Swift Package Manager only (no CocoaPods).
# Add the raven-ios-sdk package in Xcode (File > Add Package Dependencies) and link RavenIOSSDK to the extension target.
