export enum NudgeStorageKey {
  IS_FIRST_APP_LAUNCH = 'IS_FIRST_APP_LAUNCH',
  CTA_DATA = 'CTA_DATA',
  CTA_DATA_STORAGE_CLEAR_TIMESTAMP = 'CTA_DATA_STORAGE_CLEAR_TIMESTAMP',
  CTA_SNAPSHOT = 'CTA_SNAPSHOT',
  BATCH_CTA_SNAPSHOT = 'BATCH_CTA_SNAPSHOT',
  INTRANSIT_CTA_SNAPSHOT = 'INTRANSIT_CTA_SNAPSHOT',
}
